### ISSUE TITLE
Travis - Maven 3.6.2 causes build failures due to repository resolution issues

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#1390] opened 2020-01-31 16:42 UTC
Travis builds are all failing because we can't find the hypertable or async mongo client libraries, both of which are in niche maven repos. Looks like the Travis folks have some clever maven mirroring set up again that is thus falling over.

**Comment by risdenk** [comment] 2020-01-31 17:09
Hmm let me take a peek at Travis. I know there were some Travis repo caching changes. It required clearing the Travis cache and then the new repo settings were picked up.

**Comment by risdenk** [comment] 2020-01-31 17:09
Well https://travis-ci.org/brianfrankcooper/YCSB/caches apparently we don't even use caches so thats weird.

**Comment by risdenk** [comment] 2020-01-31 17:11
For completeness here is the error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (default) on project ycsb: Failed to create assembly: Unable to resolve dependencies for assembly 'package': Failed to resolve dependencies for assembly: Missing:
[ERROR] ----------
[ERROR] 1) org.hypertable:hypertable:jar:0.9.5.6
[ERROR] 
[ERROR]   Try downloading the file manually from the project website.
[ERROR] 
[ERROR]   Then, install it using the command: 
[ERROR]       mvn install:install-file -DgroupId=org.hypertable -DartifactId=hypertable -Dversion=0.9.5.6 -Dpackaging=jar -Dfile=/path/to/file
[ERROR] 
[ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]       mvn deploy:deploy-file -DgroupId=org.hypertable -DartifactId=hypertable -Dversion=0.9.5.6 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR]   Path to dependency: 
[ERROR]   	1) site.ycsb:ycsb:pom:0.18.0-SNAPSHOT
[ERROR]   	2) site.ycsb:hypertable-binding:jar:0.18.0-SNAPSHOT
[ERROR]   	3) org.hypertable:hypertable:jar:0.9.5.6
[ERROR] 
[ERROR] 2) com.allanbank:mongodb-async-driver:jar:2.0.1
[ERROR] 
[ERROR]   Try downloading the file manually from the project website.
[ERROR] 
[ERROR]   Then, install it using the command: 
[ERROR]       mvn install:install-file -DgroupId=com.allanbank -DartifactId=mongodb-async-driver -Dversion=2.0.1 -Dpackaging=jar -Dfile=/path/to/file
[ERROR] 
[ERROR]   Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]       mvn deploy:deploy-file -DgroupId=com.allanbank -DartifactId=mongodb-async-driver -Dversion=2.0.1 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR]   Path to dependency: 
[ERROR]   	1) site.ycsb:ycsb:pom:0.18.0-SNAPSHOT
[ERROR]   	2) site.ycsb:mongodb-binding:jar:0.18.0-SNAPSHOT
[ERROR]   	3) com.allanbank:mongodb-async-driver:jar:2.0.1
[ERROR] 
[ERROR] ----------
[ERROR] 2 required artifacts are missing.
[ERROR] 
[ERROR] for artifact: 
[ERROR]   site.ycsb:ycsb:pom:0.18.0-SNAPSHOT
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   google-maven-central (https://maven-central.storage-download.googleapis.com/maven2/, releases=true, snapshots=false),
[ERROR]   sonatype (https://oss.sonatype.org/content/repositories/releases/, releases=true, snapshots=false),
[ERROR]   sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/, releases=false, snapshots=true),
[ERROR]   sonatype-apache (https://repository.apache.org/content/repositories/releases/, releases=true, snapshots=false),
[ERROR]   apache-snapshots (https://repository.apache.org/snapshots/, releases=false, snapshots=true)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :ycsb
The command "mvn install -q -DskipTests=true" failed and exited with 1 during 
```

**Comment by busbey** [comment] 2020-01-31 17:19
thanks for expanding on things @risdenk

**Comment by risdenk** [comment] 2020-01-31 17:30
My guess is that the maven-assembly-plugin changed and doesn't pick up the repositories if they are specified in a module maven file.

https://github.com/brianfrankcooper/YCSB/blob/master/hypertable/pom.xml#L52

I saw something similar to this in a different project. If the repository was at the top level pom or duplicated then it worked.

It could be due to Maven versions too.

**Comment by risdenk** [comment] 2020-01-31 17:31
As a side note, I bet it would affect a bunch of projects: https://github.com/brianfrankcooper/YCSB/search?l=Maven+POM&q=%22%3Crepositories%3E%22

PS - We should update the urls to https....

**Comment by risdenk** [comment] 2020-01-31 17:35
I can't say the below is definitive (I just picked last open PR with a build that passed)

**Failing build (https://travis-ci.org/brianfrankcooper/YCSB/jobs/640408627) Maven version**
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T15:06:16Z)

**Passing build (https://travis-ci.org/brianfrankcooper/YCSB/jobs/619214678) Maven version**
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T18:41:47Z)

**Comment by risdenk** [comment] 2020-01-31 17:37
Here are the results from the master branch which might be more comparable:

**Failing build (https://travis-ci.org/brianfrankcooper/YCSB/jobs/644442146)**
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T15:06:16Z)

**Passing build (https://travis-ci.org/brianfrankcooper/YCSB/jobs/611586585)**
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T18:41:47Z)

**Comment by risdenk** [comment] 2020-01-31 17:41
Maven 3.6.1 changes - https://maven.apache.org/docs/3.6.1/release-notes.html
Maven 3.6.2 changes - https://maven.apache.org/docs/3.6.2/release-notes.html

For reference, I only briefly looked and nothing jumped off the page. Doesn't mean there isn't something.

Would probably just be easier to try it.

**Comment by risdenk** [comment] 2020-01-31 19:25
So on a hunch I looked at Maven 3.6.3 since I figured others might have reported:

https://maven.apache.org/docs/3.6.3/release-notes.html

This item specifically jumps out:

[MNG-6759] - [REGRESSION] Maven fails to use <repositories> section from dependency when resolving transitive dependencies in some cases

https://issues.apache.org/jira/browse/MNG-6759

**Comment by risdenk** [comment] 2020-01-31 23:31
I'll try to put up a PR for something around this. I have a few ideas for at least testing.

* Fixing - upgrade Maven version in Travis - I don't like this but hey
* Alternative fix - Use docker to run tests so we control Java/Maven versions? I've done this with other projects

As far as preventing others from hitting this
* Maybe use enforcement to ban specific Maven versions that are known to cause issues? - not sure maven-enforcer-plugin allows this

**Comment by risdenk** [comment] 2020-02-01 18:58
PR https://github.com/brianfrankcooper/YCSB/pull/1392

* Went with using Maven wrapper in Travis to control Maven version (easier than downloading ourselves)
* Enforce not using Maven 3.6.2 for the build

**Closed** 2020-02-01 22:44 UTC
