### ISSUE TITLE
Information about Graph Databases Benchmarking

### ISSUE THREAD

**Issue by Zaryab-Arif** [brianfrankcooper/YCSB#1203] opened 2018-07-28 13:04 UTC
Hi,
I want to benchmark hypergraph with YCSB. I have seen some bindings related to graph databases. Now can i use those bindings? 
I have created the database of hypergraph. Now the next step is adding the hypergraphdb in YCSB. So i am confused. 
Please make me clear about the difference of DB Interface layer and Client?
And please someone explain the steps through which i can get my goals.

**Comment by Zaryab-Arif** [comment] 2018-07-31 04:08
Please have a look at the below link

https://docs.google.com/document/d/1639mYA6VukNr-Wc0RWPoCI9nAY4oRjU2gux9p_QRZMM/edit

**Comment by busbey** [comment] 2018-08-12 13:55
Duplicate of #1194

**Closed by busbey** 2018-08-12 13:55 UTC
