### ISSUE TITLE
How Can I Specify Different Length for Fields

### ISSUE THREAD

**Issue by yaoyaminaco0571** [brianfrankcooper/YCSB#890] opened 2017-01-05 14:33 UTC
hi guys,
I have a cassandra table with 2 fields, I want to specify the length for first field to 64KB, and another 1KB.
I found that there is a generator : https://github.com/brianfrankcooper/YCSB/blob/master/core/src/main/java/com/yahoo/ycsb/generator/HistogramGenerator.java

It is likely match my requirement, but how to use it? 

Thanks for help.

**Comment by risdenk** [comment] 2017-01-05 16:49
Different lengths for fields are described under the core properties:

https://github.com/brianfrankcooper/YCSB/wiki/Core-Properties

**Comment by yaoyaminaco0571** [comment] 2017-01-06 02:53
I found field count & field length , but how can I set field1=64KB filed2=1KB?

**Comment by yaoyaminaco0571** [comment] 2017-01-07 11:59
Dear risden, need your help.
I can define 2 filed in 1 column family using fieldcount=2 and fieldlength=20. 
But if I want filed1 has 64K bytes and filed2 has 1K bytes, how to do it ?

**Comment by busbey** [comment] 2017-01-11 15:14
I don't think we have a set of properties for specifying multiple different fixed field lengths. It'd make a nice addition if you'd like to try adding it.

**Comment by risdenk** [comment] 2017-01-19 18:57
This could be related to #310

**Comment by risdenk** [comment] 2017-03-22 23:06
Closing since this is a duplicate of #310

**Closed by risdenk** 2017-03-22 23:06 UTC
Labels: question
