### ISSUE TITLE
why load workload before run workload?

### ISSUE THREAD

**Issue by shuyuanbingbing** [brianfrankcooper/YCSB#831] opened 2016-08-24 02:17 UTC
I found that run directly, not load, can also be normal test.

**Comment by cmatser** [comment] 2016-08-29 23:09
The "load" is to create data in the database.  The "run" is to execute statements on the data available in the database.

A "load" is insert only.  A "run" may include reads, inserts, and updates depending on the properties of your workload.

Chrisjan

**Comment by shuyuanbingbing** [comment] 2016-08-30 04:23
so can I test 100% insert by A “load”  instead of A "run"?

**Comment by cmatser** [comment] 2016-08-30 21:53
Yes.

**Comment by chinglinwen** [comment] 2016-08-31 06:11
The documents suggest to load before workload A, and delete, and load, before workload E

So for every throughput,  say 1000,10000,  then I need to delete and load twice for a single operationcount
Is this the right way to do the test,  Can I load based on the previous dataset

I tried insertstart, but it fails on the read ( the recordcount is bigger than it's operationcount because of insertstart )

Also how to run all workload , against existing data set ? ( say 100 millions already )

**Comment by cmatser** [comment] 2016-09-01 22:28
The provided workloads are examples of how you can run ycsb.  I would recommend picking the workload or workloads that make sense for you or creating your own workload that makes sense for what you want to test.

The reason the document suggests to delete and load before workload E is because workload E has inserts as part of its test run.  That means that after each test run, the overall size of the database will increase.  For testing purposes, you want to delete and load again so that you start each test run with the same number of records. 

I hope this helps.

**Comment by chinglinwen** [comment] 2016-09-02 07:03
I understand to keep the number correct when testing,  My colleague says its not real,   our business data set may continually insert into database,  I mean can I do a test, that have 1 millions data set already exists in the database,  and then do that test based upon.

At least for now, I have following issue
- it's primary key duplicate, make it insert fail ( when not delete after first run ) 
- only one time test are making sense enough( delete,and load), but iterate many ( 1000 * 10 step, where step is 1000 or bigger ) make this testing very long time

by the way, how to using, the recordcount and operationcount correctly,  currently I just make them the same,  is there a example of doing all the test ( for multiple time iterate ) ?

I wrote [ycsb_starter ](https://github.com/chinglinwen/ycsb_starter) and ycsb2graph, I'm not sure it's the correct way or not?

**Comment by cmatser** [comment] 2016-09-08 00:25
I believe there is an option for key start value.  So, then you could run the test multiple times without deleting everything if you update the key insert start value after each run.

Try property 'insertstart'.

**Comment by chinglinwen** [comment] 2016-09-08 02:51
I tried insertstart before,  but it then making read-failed, to be sure, I tried again the following

> - the insertstart is manual select count from the table
> - load and test just a function, shorthand for ycsb testing, a means workloada, 100 means recordcount and operationcount, except modify by the third argument ( it will use the 100, the second parameter)
> - I reduce the number to small, for quick result, in real test, I may load 1 millions first, and do the test on it ( no delete )

#test insertstart again to confirm 2016-9-8
load a 100 "-p insertstart=100"
run a 100
	# a b c f are okay
#run d 104 failed, duplicate key

run d 100 "-p insertstart=100"	#insert fail, without record count # revised, ok (count=103)
	#so it is need to correct with load count?
run d 100 "-p insertstart=103"
	#for every workload, run again will be failed
#confirm it, by reload
load a 100 "-p insertstart=208"
run d 100 "-p insertstart=308"
	#insert-failed, duplicate key
	
#it's recordcount not correct?
run d 100 "-p insertstart=308 -p recordcount=408"		#read fail
run d 100 "-p insertstart=313 -p recordcount=413 -p operationcount=100"	#read fail
run d 100 "-p insertstart=319 -p recordcount=100 -p operationcount=419"	#insert fail
run d 100 "-p insertstart=319 -p recordcount=419 -p operationcount=419"	#read fail

load d 100 "-p insertstart=345"	#key duplicate
load a 100 "-p insertstart=408"	#key duplicate
load a 100 "-p insertstart=408 -p recordcount=508"	#key duplicate
load a 100 "-p insertstart=408"	#key duplicate
	#it seems old test insert, makes the insert fail
	#let's clean up , load again from the beginning
load d 100	#ok
run d 100 "-p insertstart=100"		#ok
load a 100 "-p insertstart=108"	#ok
run d 100 "-p insertstart=208"		#insert fail
run d 100 "-p recordcount=308 -p insertstart=208 -p insertcount=100"	#read fail

#try workloade (early test for the workloade, not continue from above )
run e 100 "-p insertstart=103"	#0 operations; est completion in 106751991167300 days 15 hours 
run d 100 "-p recordcount=306 -p insertstart=206"		#read fail

here are output log for more detail ( little mess in there )
[output_log.txt](https://github.com/brianfrankcooper/YCSB/files/460732/output_log.txt)

some select and delete is enter at other terminal ( not in the log )

For the above test, I'm not found a way to do the test based on existing data-set without fail
What I want to test is no matter how the data set already exists in the table, do test based on it ( so no need to delete before the test )

Let's simplify it as
load a 100
run d 100
load a 200
run d 200
run e 200( auto count)

**Comment by cmatser** [comment] 2016-09-12 23:18
You need to use the properties a little differently.

**insertorder**: should records be inserted in order by key (“ordered”), or in hashed order (“hashed”) (default: hashed)
**operationcount**: number of operations to perform.
**recordcount**: number of records to load into the database initially (default: 0)
**insertstart**: starting record number for inserts

You'll want to make sure you are using ordered inserts for both load and run.  For load, `insertstart` should be unset.  For runs, you can set `insertstart` to be the `recordcount` from the load. 

So, if you want to start with a hundred records:
load insertorder=ordered, recordcount=100

Then if you want to do multiple runs without delete/re-load you have to increment your `insertstart` to a number beyond what the number newly inserted records.  For example, if you work load was 95% read and 5% insert, you could try a series of runs like:
run1 insertorder=ordered, operationcount=100, insertstart=110
run2 insertorder=ordered, operationcount=100, insertstart=120
run3 insertorder=ordered, operationcount=100, insertstart=130

I incremented `insertstart` by 10 instead of 5 (105, 110, 115) to be safe, because the read/write proportion is probability calculation, not an exact one.

**Comment by chinglinwen** [comment] 2016-09-13 06:47
insertorder do solve my problems(especially for workloade test without delete first), I have done test this way

load a 100
run a 100
run d 100
load a 100

run e 100 "-p insertorder=ordered -p insertstart=203 -p operationcount=100 -p recordcount=303"
	#ok
load a 100 "-p insertstart=206"	#ok, got 306
run e 100 "-p insertorder=ordered -p insertstart=306 -p operationcount=100 -p recordcount=406"
	#confirmed, ok

#check arbitrary test ( current count 312 )
run e 100 "-p insertorder=ordered -p insertstart=312 -p operationcount=100 -p recordcount=412"
  #ok

the last run, makes me assure that I can do any workloade test now, without delete

Thank you !

**Comment by chinglinwen** [comment] 2016-09-13 07:51
The accumulate mentioned above,  for workloadd,  It is not correct, it is no error is because it provided all records count( not the accumulate count )

Say the table has 680 count ( for real test, it maybe 100 millions )
load a 100 "-p insertstart=680"
run d 100 "-p insertstart=780"
	#insert fail
run d 100 "-p insertstart=780 -p insertorder=ordered"
	#read fail

It only works, when the count is equal to the table's record count ( _for load 100, but workloadd need to run for 100 millions count, because there are that much data exists,  How can I just do workloadd test for 100 only?_ )

I tried using different recordcount and operationcount, it is just doesn't work for workloadd

say current count is 825
run d 100 "-p insertorder=ordered -p insertstart=825 -p operationcount=100 -p recordcount=925"
	#read fail

I think workloadd's requestdistribution=latest causes this problem ( either read or insert fail )

How can I have a arbitrary testing for workloadd?

**Comment by cmatser** [comment] 2016-09-15 21:37
You are using `insertorder=ordered` for the loads too correct?

I think the last thing you said regarding `requestdistribution` is correct.  Till now, I thought you were having an issue with inserts.  If you are having a problem with `requestdistribution`, then the issue is on read.

You are trying to read a record that doesn't exist?  That could be because your `recordcount` property is too high.  You said the count is 825, but you set `recordcount=925`.  You've included an extra 100 records for the request distribution that do not exist.  That seems to be the problem.

I'm wondering if you need to set `insertstart=826` when there are 825 records.  You'll have to experiment and see.

Chrisjan

**Comment by chinglinwen** [comment] 2016-09-18 02:08
> You are using insertorder=ordered for the loads too correct?

Have insertorder for loads solved the problem.

load a 100 "-p insertorder=ordered"
load a 100 "-p insertorder=ordered -p insertstart=100"
run d 100 "-p insertorder=ordered -p insertstart=200 -p operationcount=100 -p recordcount=200"
	#ok
run d 100 "-p insertorder=ordered -p insertstart=208 -p operationcount=100 -p recordcount=208"
	#ok
run d 50 "-p insertorder=ordered -p insertstart=215 -p operationcount=50 -p recordcount=215"
	#ok
load a 100 "-p insertorder=ordered -p insertstart=219"
run d 50 "-p insertorder=ordered -p insertstart=319 -p operationcount=50 -p recordcount=319"
	#ok

I do workloade test too, it's ok too ( but recordcount = operationcount+insertstart )

Conclusion,  ordered is a must for pre-load concept ( that no need delete first )
After all the combination is little tricky.

Thank you Chrisjan.

**Comment by chinglinwen** [comment] 2016-09-18 07:01
> I'm wondering if you need to set insertstart=826 when there are 825 records.

It need to plus 1 , so 826 is good, insertstart=( rows count + 1 ), otherwise duplicate key happens

I found the recordcount for workloade cause a problem (while recordcount = operationcount+insertstart )

say currents row count is 10
[root@test ycsb_starter2]# $dosql "select YCSB_KEY from usertable order by YCSB_KEY;"
10 rows
YCSB_KEY
user1
user10
user2
user3
user4
user5
user6
user7
user8
user9

after run workloade
`-P ../workloads/workloade -p insertorder=ordered -p insertstart=11 -p recordcount=20 -p operationcount=10 -t`

[root@test ycsb_starter2]# $dosql "select YCSB_KEY from usertable order by YCSB_KEY;"
11 rows
YCSB_KEY
user1
user10
user2
user20
user3
user4
user5
user6
user7
user8
user9

It insert user20 to the table, this user20 will later cause duplicate key

load a 20
` -P cockroachDB.properties -s -P ../workloads/workloada -p insertorder=ordered -p insertstart=12 -p operationcount=20 -p recordcount=20 -load`

Error in processing insert to table: usertableorg.postgresql.util.PSQLException: ERROR: duplicate key value (YCSB_KEY)=('user20') violates unique constraint "primary"

How to solve this problem, I tried different combination for workloade, only when recordcount = operationcount+insertstart works, it then introduce a extra problem for load

say current row count 200
run e 100 "-p insertorder=ordered -p insertstart=201 -p operationcount=100 -p recordcount=100"
	#0 operations; est completion in 106751991167300 days 15 hours 
run e 100 "-p insertorder=ordered -p insertstart=201 -p operationcount=100 -p recordcount=201"
	#0 operations; est completion in 106751991167300 days 15 hours
run e 100 "-p insertorder=ordered -p insertstart=201 -p operationcount=100 -p recordcount=301"
	#ok
#inserted 5 rows
user301
user302
user303
user304
user305
# I think it use recordcount rather than insertstart

Now I can't do arbitrary load, because workloade skipped some key ( make it later duplicate)

How can I fix this problem?

**Comment by cmatser** [comment] 2016-09-19 04:34
I think we are not using `recordcount` correctly.  Try `recordcount` set to the current number of records.  I saw in the above you did the following:
-P ../workloads/workloade -p insertorder=ordered -p insertstart=11 -p recordcount=20 -p operationcount=10 -t

However, there were only 10 records.  So instead, try with `recordcount=10`.

Chrisjan

**Comment by chinglinwen** [comment] 2016-09-19 05:08
recordcount=10, will cause infinit time

[root@test ycsb_starter2]# $dosql "select YCSB_KEY from usertable order by YCSB_KEY;"
user1
user10
user2
user3
user4
user5
user6
user7
user8
user9
[root@test ycsb_starter2]# count
10
[root@test ycsb_starter2]# run e 10
...
-P ../workloads/workloade -p insertorder=ordered -p insertstart=11 -p recordcount=10 -p operationcount=10 -t
YCSB Client 0.10.0
Command line: -db com.yahoo.ycsb.db.JdbcDBClient -P mysql.properties -s -P ../workloads/workloade -p insertorder=ordered -p insertstart=11 -p recordcount=10 -p operationcount=10 -t
Loading workload...
Starting test.
Adding shard node URL: jdbc:mysql://192.168.100.243:3307/ycsb
2016-09-19 13:01:59:915 0 sec: 0 operations; est completion in 0 seconds 
Using shards: 1, batchSize:-1, fetchSize: -1
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
2016-09-19 13:02:09:859 10 sec: 0 operations; est completion in 106751991167300 days 15 hours 

see more detail in the attachment ( extra test for recordcount=20 )
[infinit_time.txt](https://github.com/brianfrankcooper/YCSB/files/479242/infinit_time.txt)

**Comment by cmatser** [comment] 2016-09-22 15:34
You may have stumbled on a bug.  I'm sorry I don't have the time to really look at it.  Please submit a new issue to detail this in the simplest terms possible.  I think the basic issue to solve is to load once, and then do multiple runs that involve inserts while adjusting the properties to avoid collisions.

I'm going to close this issue.  Thank you for your time on this.

**Closed by cmatser** 2016-09-22 15:34 UTC
