### ISSUE TITLE
cassandra tests should use prepared statements rather than the query builder

### ISSUE THREAD

**Issue by rustyrazorblade** [brianfrankcooper/YCSB#822] opened 2016-08-11 20:00 UTC

**Comment by busbey** [comment] 2016-08-11 20:06
duplicate of #458 probably?

Interested in putting together a PR?

**Comment by rustyrazorblade** [comment] 2016-08-11 20:10
oops, sorry, i searched for open cassandra issues and didn't see it.  I think I can put together a PR for this, it looks reasonably straightforward.

**Comment by risdenk** [comment] 2016-09-26 14:11
Closing as duplicate of #458

**Closed by risdenk** 2016-09-26 14:11 UTC
