### ISSUE TITLE
Release version 0.4.0

### ISSUE THREAD

**Issue by allanbank** [brianfrankcooper/YCSB#409] opened 2015-09-17 01:40 UTC
Currently for the 0.4.0 release the following items have already been merged:
* #392 - Separate HBase v0.9x and v1.x bindings.
* #371 - Make hdrhistogram default measurement type.

Of particular note is that #371 introduces two *incompatibilities* with previous releases:
* Default measurement changed from histogram to hdrhistogram
  Users who want previous behavior can set the 'measurementtype' property to 'histogram'
* Reported 95th and 99th percentile latencies now in microseconds (previously in milliseconds)

After the RC0 release is created we need to verify that both of those changes are working as intended. Once both items are tested I will create a RC1. 

Once the RC1 release has been created I will ask for everyone to test as many of the binding as possible. I think the minimum set should be (as they were tested in 0.3.0 or saw a recent update):
* Apache Accumulo 1.6.0 via the accumulo binding.
* Apache Cassandra 2.0.15 via the cassandra-cql and cassandra-10 bindings.
* Apache HBase 1.0.0 via the hbase10 binding.
* Apache HBase 0.98.x via the hbase098 binding.
* Apache HBase 0.94.x via the hbase094 binding.
* MongoDB via the mongodb and mongodb-async bindings. 
* Tarantool 1.6.1 via the tarantool binding.
* Aerospike 3.5.15 via the aerospike binding.

While I will not pester anyone about testing the bindings until after the RC1 I want to encourage everyone to test as soon as RC0 is released.

In the interest of getting the release out quickly I am going to try and avoid patches unless absolutely necessary. The flip side of that is I want to give folks a chance to get more changes into the baseline so I won't do the initial RC0 build until September 21st. I will plan to do the RC1 build about a week later on September 28th and hope for a final release before October 8th. To summarize:
* RC0 - September 21st
* RC1 - September 28th
* 0.4.0 - before October 8th.

**Comment by busbey** [comment] 2015-09-17 11:42
Sounds like a good plan.

As things currently stand, #392 also introduces an incompatible change because it replaces the behavior of the 'hbase' binding with 'hbase098'.

**Comment by busbey** [comment] 2015-09-17 11:46
Just realized #392 also broke compat by renaming 'hbase-10' to 'hbase10'.

As an aside, back in 0.3.0 only hbase against version 1.0.0 was tested. AFAIK after we determined 0.98 and 0.94 didn't work back in 0.2.0 we didn't retest due to time.

**Comment by cmccoy** [comment] 2015-09-17 20:47
@allanbank - thanks for doing this!

> As an aside, back in 0.3.0 only hbase against version 1.0.0 was tested. AFAIK after we determined 0.98 and 0.94 didn't work back in 0.2.0 we didn't retest due to time.

That's right. Regarding the version incompatibilities: I renamed all bindings to be explicit about which version they target. Since `bin/ycsb` selects a binding based on the component of the database name prior to a `-` character, I renamed `hbase-10` as well. I'd be happy to try and accommodate other suggestions prior to v0.4.

**Comment by allanbank** [comment] 2015-09-21 23:57
[0.4.0-RC1](https://github.com/brianfrankcooper/YCSB/releases/tag/0.4.0-RC1) has been cut.  Let the testing begin.

For this first phase of testing please focus on the following issues:
* #392 - Separate HBase v0.9x and v1.x bindings.
* #371 - Make hdrhistogram default measurement type.
* #327 - Race condition between insert and read/update operations. (via PR #364)

I am personally going to start with #327.

Thanks,
Rob

**Comment by allanbank** [comment] 2015-09-23 01:04
To verify #327 I ran workload D adjusted to 10,000,000 operations and 50% read / 50% insert using the mongodb-async binding and saw no return=1 values. This also used the new default hdrhistogram.

I am going to run the workload again with the measurementtype=histogram reporting to make sure that works too.

Rob.

**Comment by allanbank** [comment] 2015-09-24 00:52
measurementtype=histogram works as expected.

That I think leaves #392. 

@cmccoy @busbey - Will you have some time in the next week or so to try the different HBase bindings? Do you have access to v1.0, v0.98 and v0.94 clusters? I have a small VM farm I can throw a small cluster onto but need to know which version I should target.

Thanks,
Rob

**Comment by cmccoy** [comment] 2015-09-24 01:30
I'm sorry - I'm just getting back from sick leave, and am a bit swamped.
FWIW, I tested against #392 against HBase 1.0.1.1, HBase 0.98.14 and 0.94.27 prior to merging, although that missed any subsequent commits to master.

**Comment by gkamat** [comment] 2015-09-24 01:41
I'll sign up to test RC1 against the different HBase bindings.  Will try to have results by mid-next-week.

**Comment by busbey** [comment] 2015-09-24 02:42
I'm planning to do windows and accumulo testing tomorrow evening. Given the work I already did on #407 I think I can test JDBC against MySQL as well this weekend.

**Comment by busbey** [comment] 2015-09-24 02:43
@tlopatic could we trouble you to test Aerospike again?

@bigbes how's your schedule looking for Tarantool?

**Comment by tlopatic** [comment] 2015-09-24 09:30
Sure! Just tested, everything as expected on Aerospike with RC1. And I like the new measurement type default.

**Comment by Thomas-Yang** [comment] 2015-09-25 18:08
I am testing with Cassandra 2.0.15 on a local machine. It gives me the following errors:
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1 ([localhost/127.0.0.1] Unexpected error during transport initialization (com.datastax.driver.core.TransportException: [localhost/127.0.0.1] Channel has been closed)))
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:158)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)

**Comment by busbey** [comment] 2015-09-27 15:20
I ran through the recommended workloads with Accumulo 1.6:

* Ran into known issue #340 again
* Additional incompatible change in hdrhistogram, following measurements are exported as floating instead of as integers:
  * number of operations
  * min latency
  * max latency
  * 95p latency
  * 99p latency 
* workload d fails with
```bash
java.lang.RuntimeException: Too many unacknowledged insertion keys.
        at com.yahoo.ycsb.generator.AcknowledgedCounterGenerator.acknowledge(AcknowledgedCounterGenerator.java:44)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionInsert(CoreWorkload.java:769)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:575)
        at com.yahoo.ycsb.ClientThread.run(Client.java:329)
```
this workload performed correctly in 0.2.0 and 0.3.0.
* noticed workload e doesn't export a measurement of SCAN operations. checked and it didn't do this in 0.3.0 or 0.2.0.

**Comment by tlopatic** [comment] 2015-09-27 16:09
Interesting. The exception in workload D is really odd. It's part of the fix for "inserted records are read before they've actually been inserted", #327.

How exactly (# of threads, # of records, etc.) did you run workload D to produce the exception?

A bit of background. The fix works as follows: As before, doTransactionInsert() invokes nextInt() to obtain a new key. That key would be instantaneously passed over to lastInt(), even before the insert completed. Now, with the fix, that key is only passed over to lastInt() after doTransactionInsert() calls acknowledge(), which it only does after the insert completed. So, now we never try to read keys generated by nextInt(), whose insert is still pending.

The semantics of lastInt() are "keys up to X have been inserted into the database", X being the value reported by lastInt(). What complicates the fix a little is that acknowledgements can arrive out of order. Suppose that we start three insert operations with keys 1000, 1001, and 1002. Suppose that they complete in the order 1002, 1001, 1000. Ultimately, we want lastInt() to report 1002. However, we want it to only report 1002, after 1001 and 1000 have been inserted as well.

What the fix does is to keep track of the acknowledged keys in a sliding window. That window has 1,000,000 entries. Whenever there's a contiguous chunk of N keys at the beginning of this window, we increase the value reported by lastInt() by N and also shift the window by N.

What probably happened in your case is that the window cannot be moved, because a key is missing. A thread probably invoked nextInt() and then got stuck somewhere. In the meantime, the other threads happily invoked nextInt() / acknowledge(), up to 1,000,000 times, filling up the window. This then caused the exception.

Theoretically, it could just be a thread starvation issue, where one thread invokes nextInt(), then never sees the CPU again, and thus keeps the sliding window from sliding. But that would mean that the other threads got to do 1,000,000 insertions without the starved thread getting to complete its insertion. This is definitely possible, but maybe not the most likely explanation.

I'd like to first rule out something else. Could there be an issue with the Accumulo driver? Something that locks up one of the YCSB threads, which then blocks the sliding window. It's something that we might not necessarily have noticed before, as a single blocked thread didn't have that huge an impact on a YCSB run before.

Thomas

**Comment by busbey** [comment] 2015-09-27 16:31
I used this older version of the "run ycsb workloads" helper that I've posted before:

https://gist.github.com/busbey/fcb6f63128f3a1a85541

as it's run, should be 30 threads and 429496729 operations.

**Comment by busbey** [comment] 2015-09-27 16:34
how would we test for a blocked thread? I haven't destroyed the tables from this test run, so if you have a suggestion of post-hoc verification I could check that.

**Comment by allanbank** [comment] 2015-09-27 19:24
@busbey - 

Workload D issue - I think a stuck thread would manifest as missing entries in the table. Can you try running a pure read workload on the table that reads all of the items from the load + the (0.05*429496729) that should have been inserted?

Workload E - Your script does two loads for workload E instead of a load and run. Could that be the cause of the missing SCAN metrics?

Rob.

**Comment by busbey** [comment] 2015-09-27 19:42
> Workload D issue - I think a stuck thread would manifest as missing entries in the table. Can you try
> running a pure read workload on the table that reads all of the items from the load + the
> (0.05*429496729) that should have been inserted?

Sure I can do that. Would it be faster for me to build summary statistics of the underlying table in Accumulo?

> Workload E - Your script does two loads for workload E instead of a load and run. Could that be the
> cause of the missing SCAN metrics?

lol. yeah. that's what I get for relying on the old version that was convenient. I'll rerun workload e load + run on 0.3.0 and 0.4.0 this evening.

**Comment by allanbank** [comment] 2015-09-27 19:49
On stats across the table. The problem is that the integer value is hashed (via Fowler-Noll-Vo) before it is prefixed with "user". The easiest way I could think to find the gap across the hashed values is to just do a sequential scan.

**Comment by tlopatic** [comment] 2015-09-28 07:53
Or, if the issue is reproducible, you could set the "insertorder" property to "ordered" and run the test again. That would skip the hashing and just do "user" + nextInt() for the keys.

**Comment by gkamat** [comment] 2015-10-02 19:02
I ran the standard workloads 'a' through 'f' on HBase versions 0.94, 0.98 and 1.0, using a local machine.  All of them went through fine.

I did not have comparative runs with 0.94 and 0.98 which weren't supported directly before, but runs against HBase 1.0 are similar between YCSB 0.3 and 0.4.

Workload D was run in two modes, one the default and the other with a 50-50 mix of reads and inserts to make sure the issue reported earlier was not encountered.

Did not look into the measurement export output as Sean did.

I will re-run next week with a small cluster prior to release.

**Comment by allanbank** [comment] 2015-10-03 18:01
@gkamat - Thanks for testing on the different HBase versions.

@busbey - Where you able to detect missing entries in the table? The the issue with workloadd always happen (e.g., reproducible) or did we get unlucky? Mind sharing the size of the cluster you used and posting the workload file you used?

**Comment by busbey** [comment] 2015-10-04 04:00
I'm checking the cluster now. If it reproduces I'll add a test.

the cluster was 5 workers and I used a single client. the workload was the standard we ship (with some options given above in the runner script).

**Comment by busbey** [comment] 2015-10-04 04:15
now that workload e is actually running, it failed too:

````bash
java.lang.RuntimeException: Too many unacknowledged insertion keys.
        at com.yahoo.ycsb.generator.AcknowledgedCounterGenerator.acknowledge(AcknowledgedCounterGenerator.java:44)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionInsert(CoreWorkload.java:769)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:575)
        at com.yahoo.ycsb.ClientThread.run(Client.java:329)
java.lang.ArrayIndexOutOfBoundsException: -483648
        at com.yahoo.ycsb.generator.AcknowledgedCounterGenerator.acknowledge(AcknowledgedCounterGenerator.java:47)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionInsert(CoreWorkload.java:769)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:575)
        at com.yahoo.ycsb.ClientThread.run(Client.java:329)
````

workload d failed the same was as before as well. scanning table next.

**Comment by busbey** [comment] 2015-10-04 05:40
no gaps found 

```bash
ycsb]$ accumulo shell -u ycsb -p password -e "scan -t ycsb -np -c family:field0" | cut -f 1 -d ' ' | sort -V | cut -d'r' -f 2 | python -c 'import fileinput
> last=-1
> for i in fileinput.input():
>   if (last+1) != int(i):
>     print("missing: {0} current: {1}".format((last+1), i))
>   last=int(i)
> '
ycsb]$
```

I believe this wouldn't detect if none of the workload d inserts succeeded at all.

I'll make a test.

**Comment by tlopatic** [comment] 2015-10-04 11:20
@busbey Ah, wait a second. Sorry. A stuck thread wouldn't result in missing entries. As soon as one thread is stuck, lastInt() will be incremented up to the stuck thread's key, without gaps.

At that point, the stuck thread's key will be the lowest key in the sliding window and thus the sliding window cannot be advanced. The other threads will happily keep inserting, and at some point, the sliding window will overflow.

So, the best thing to do would probably be to insert two debug log statements in doTransactionInsert() of the CoreWorkload class:

  * A message saying "key generated" right after the invocation of nextInt().
  * A message saying "about to acknowledge key" right before the invocation of acknowledge() in the "finally" block.

Let's also include the thread ID and the key in the messages. Any "key generated" message that's not followed by an "about to acknowledge key" message would indicate a stuck thread.

We should then also validate that the database table contains keys up to one below the stuck thread's key, i.e., max(keys in table) == (stuck thread's key) - 1.

**Comment by allanbank** [comment] 2015-10-07 02:27
I got a single node accumulo instance running yesterday and finally got to running @busbey 's  script today.  It actually fails really quickly. The tell tail exception (I think) is this one: 

```
java.lang.ArrayIndexOutOfBoundsException: -483648
        at com.yahoo.ycsb.generator.AcknowledgedCounterGenerator.acknowledge(AcknowledgedCounterGenerator.java:47)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionInsert(CoreWorkload.java:769)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:575)
        at com.yahoo.ycsb.ClientThread.run(Client.java:329)
```

I think what is happening is that the large offsets that @busbey  is using is causing the integer value to roll over and the the modulo operator fails to remove the sign and everything goes down hill from there. I have a path to convert the modulo into a bit mask which should solve the issue.  The test is running now.

**Comment by tlopatic** [comment] 2015-10-07 06:31
@allanbank Ooooh, right! So the thread doesn't get stuck - it crashes.

Regarding the wrap-arounds - I have been a little worried about them in general. They seem to cause all kinds of issues in YCSB, which is why I assumed that they are not supposed to happen in the first place:

  * A positive value turning into a negative value could break comparisons. Suppose that we've inserted enough records for a total of 2^31 records in the table. That would turn lastInt() negative. We'd go from 2^31 - 1 to -2^31. Problem: Reads only read records with keys that are "<= lastInt()". Now we would only read 1 key, key -2^31, and ignore all the other 2^31 - 1 keys in the table.

  * This problem is not specific to workloads that actually insert. Suppose that you have a workload with exactly 2^31 records ("recordcount" property). As above, we would only ever read this single record. @busbey is aware of this and the script uses exactly 2^31 - 1 keys. But other users may not be aware of it.

  * Sure, we could now try to fix this for the "positive becomes negative" case. But that would just make us wrap around at 2^32 instead with similar problems.

I think that the more general fix would be to make YCSB use long-valued keys throughout.

Sure, we can fix the crash in AcknowledgedCounterGenerator. But I think this is just a symptom of a larger issue. All the other issues above, which don't lead to crashes but to inaccurate measurements, would still prevail. The "<= lastInt()" comparison for reads would still fail, for example.

Shall we maybe for now do the following instead of changing AcknowledgedCounterGenerator?

  * Introduce parameter validation before the benchmark runs, which makes sure that the user doesn't specify more than 2^31 - 1 records. Print an error message and abort, if they do.

  * If the workload contains inserts, add a dynamic check during the benchmark run that detects when we reach 2^31 - 1 records and then cleanly shuts down the benchmark run - instead of crashing with an exception.

For one of the next versions, we might want to look into migrating things to long-valued keys.

Thomas

**Comment by allanbank** [comment] 2015-10-08 02:09
Thomas - 

First I agree with everything you said. We need to properly support datasets with more than 2^31 entries and that the pre-0.4.0 runs using more that 2^31 entries are probably, at best, not well defined. 

I disagree that adding a temporary patch that breaks previously working runs is the right approach. The patch I have (it works by the way) I think will get use over the 0.4.0 hump and we can create a real fix by changing all of the ids and offsets from ints to longs. 

FYI - Someone already started the conversion to longs in #126 but it appears to have build/test issues and won't merge cleanly. I have not looked at it closely enough to tell it it is faster to start clean or use it a as a base to build from.

I just created a pull request for the mask fix if someone can review. 

Assuming the change is acceptable I would also like someone to give a :+1: here to pulling into 0.4.0.

Thanks,
Rob.

**Comment by busbey** [comment] 2015-10-08 03:00
IIRC, building off of #126 should be short work. Alternatively we might be able to get the contributor going again if there's active interest.

**Comment by busbey** [comment] 2015-10-08 03:02
oh, also :+1: on getting this AcknowledgedCounterGenerator specific fix in for 0.4.0 and then pushing to get the long stuff done for next time.

**Comment by tlopatic** [comment] 2015-10-08 09:35
@allanbank Sure, completely makes sense. Maybe this is not the time to make major changes to 0.4.0.

I just took a look at the fix and, other than one really minor thing regarding the loop that we can probably neglect - famous last words! :) -, everything looks good to me.

Even if migrating to long-typed keys is too much for the next release, though, I'd like to suggest that in that release we at least warn users, if the key becomes negative (during the load phase as well as during the actual benchmark run).

**Comment by allanbank** [comment] 2015-10-11 01:46
I just posted the 0.4.0-RC2 with the fix for workloadd from #427.

https://github.com/brianfrankcooper/YCSB/releases/tag/0.4.0-RC2

For those that did not follow the discussion in #427 we also found an issue with workloade that goes back to before 0.3.0.  I have filled issue $31 to address it in a future release.

If everyone can give RC2 a quick once over I think we are close to getting the release out. 

I will run my MongoDB suite shortly.   
@busbey - Can you run the workloadd one more time against the RC2? Also did you ever do the windows testing? 
@bigbes - Did you get a chance to try out one of the RCs with Tarantool?
@Thomas-Yang - I think you Cassandra issue got lost in the noise. Did you ever get Cassandra working with the RC?

Rob.

**Comment by allanbank** [comment] 2015-10-11 20:47
The normal suite of MongoDB runs worked.

**Comment by busbey** [comment] 2015-10-12 05:33
Accumulo checked out fine on RC2 after using the workaround for #384.

Honestly I don't remember if I ran windows. Since I didn't write it down here, I'll do it again.

**Comment by busbey** [comment] 2015-10-12 07:04
my windows machine did not have a good evening. :/ will try again tomorrow.

**Comment by tlopatic** [comment] 2015-10-12 11:03
RC2 looks fine with the Aerospike binding.

**Comment by busbey** [comment] 2015-10-13 11:13
windows works-at-all.  #335 is still an issue, but I don't think that surprises anyone.

Ran into #434, which is pretty bad. Only solution I can think of for now is to add a profile that disables hbase 1.0 tests on windows. @cmccoy what do you think?

**Comment by cmccoy** [comment] 2015-10-13 15:34
Ouch, that's not great. @busbey - how about skipping those tests on Windows [Assumption](http://junit.sourceforge.net/javadoc/org/junit/Assume.html)?  cmccoy@7501ad03254bee799f1093adb9ad52f27261c9c4 does that (mostly because I'm less familiar with Maven profiles).

I don't have a Windows machine to test against, but the above skips the test when I negate the condition in `isWindows()`.

**Comment by busbey** [comment] 2015-10-13 16:26
an Assumption would be even better since the test will show as skipped (rather than as not existing via a profile).

**Comment by busbey** [comment] 2015-10-14 13:55
I merged #435 (which fixes #434) and cherry-picked it back to the 0.4.0-staging branch.

**Comment by allanbank** [comment] 2015-10-15 02:14
Pushed out a RC3: https://github.com/brianfrankcooper/YCSB/releases/tag/0.4.0-RC3

One last round of sanity checks.

**Comment by allanbank** [comment] 2015-10-15 02:36
Running the rat check and it is flagging the doc/javadoc/package-list file. Looks like at some point the generated javadoc was getting committed to the repo. Do we want to continue that practice as part or released or should we jettison the doc/javadoc directory?

I would vote to jettison.

**Comment by cmccoy** [comment] 2015-10-15 14:38
:+1: to jettisoning.

**Comment by cmccoy** [comment] 2015-10-15 14:38
I think we should consider pulling #441 into 0.4.0.

**Comment by cmccoy** [comment] 2015-10-15 18:06
Cherry-picked #441 into `0.4.0-staging`.

**Comment by allanbank** [comment] 2015-10-15 19:51
I just pulled in the license changes and apache-rat now builds clean.

I created an RC4: https://github.com/brianfrankcooper/YCSB/releases/tag/0.4.0-RC4

**Comment by busbey** [comment] 2015-10-20 03:46
looks good! do we have draft release notes I can help by reviewing?

**Comment by allanbank** [comment] 2015-10-21 00:44
Draft Release notes:

https://gist.github.com/allanbank/13ea6ba0a249414c1ac4#file-0-4-0-release-notes-md

**Comment by busbey** [comment] 2015-10-21 03:47
Good first pass!

A few of notes:

number #441 should get called out, since it means a bunch of folks likely have incorrect results.

There are a number of datastore bindings that have issue numbers listed that are from previous releases, I'd leave those out (see e.g. as done in 0.3.1)

> Tarantool 1.6.1 via the tarantool binding (see #292, #319).

Did @bigbes get a chance to test Tarantool?

> Race condition between insert and read/update operations. (see #327).

I'd add a link to #427 as well, just as e.g. (see #327 and #427)

**Comment by allanbank** [comment] 2015-10-22 02:24
I made the changes to the release notes.

I thought I had seen @bigbes report that he had run tarantool with a RC but now I can't find it. Rather that drop it from the tested set I went ahead and installed tarantool and ran the basic suite with 100,000 operations. Everything looked good to me.

Any reasons not to cut a 0.4.0?

Rob.

**Comment by cmccoy** [comment] 2015-10-22 02:26
Sounds good to me.  Thanks!

**Comment by busbey** [comment] 2015-10-22 04:54
:ok_woman:

**Comment by allanbank** [comment] 2015-10-23 02:06
Release is done!
    https://github.com/brianfrankcooper/YCSB/releases/tag/0.4.0

Final pull request to update the README is also ready and will close this issue.   
   https://github.com/brianfrankcooper/YCSB/pull/445

**Closed** 2015-10-23 03:46 UTC
