### ISSUE TITLE
Parallel load and run in MySQL cluster

### ISSUE THREAD

**Issue by ssizmaster** [brianfrankcooper/YCSB#1277] opened 2019-01-13 18:51 UTC
Hi,
I would like to know how to load data and run  Workloads A and C in parallel in MySQL NDB  Cluster with two nodes?
Thank you in advance.

**Comment by busbey** [comment] 2019-06-04 03:31
closing as duplicate of #1311

**Closed by busbey** 2019-06-04 03:31 UTC
