### ISSUE TITLE
Proposal of supporting Application Default Credentials when benchmarking Cloud Datastore

### ISSUE THREAD

**Issue by k1xme** [brianfrankcooper/YCSB#779] opened 2016-06-26 02:34 UTC
For now, if we want to benchmark Cloud Datastore, we have to pass p12 key file and service account params to YCSB, which is inconvenient when we run the benchmark inside Google Compute Engine or if we want to call YCSB via PerfKitBenchmark.

The plan:
Instead of throwing exceptions when `googledatastore.privateKeyFIle` or `googledatastore.serviceAccount` are not set, we try to create Datastore client using ADC by calling:
1)
Use gcloud APIs.
This is more straightforward API than v1beta3, very easy to use. But requires changes in all call sites.
[gcloud API Documentation](http://googlecloudplatform.github.io/gcloud-java/0.2.3/index.html)
I prefer this one.
> import com.google.cloud.datastore.Datastore;
import com.google.cloud.datastore.DatastoreOptions;
Datastore datastore = DatastoreOptions.defaultInstance().service();

2)
Keep using v1beta3 APIs. No code change needed in all the call sites.
>import com.google.datastore.v1beta3.client.Datastore;
import com.google.datastore.v1beta3.client.DatastoreFactory;
import com.google.datastore.v1beta3.client.DatastoreHelper;
import com.google.datastore.v1beta3.client.DatastoreOptions;
> DatastoreOptions options = DatastoreHelper.getOptionsFromEnv().projectId(datasetId).build();
   Datastore datastore = DatastoreFactory.get().create(options);

**Comment by kruthar** [comment] 2016-06-27 01:50
Possibly a duplicate of #510 posed by the original author of the googledatastore binding. This extra functionality would be much appreciated, would you be up for submitting a patch?

**Comment by risdenk** [comment] 2016-09-27 14:58
Closing as duplicate of #510. @k1xme please open a PR if you can!

**Closed by risdenk** 2016-09-27 14:58 UTC
