### ISSUE TITLE
When can the mongo-async driver support the scram-sha-1 authentication mechanism?

### ISSUE THREAD

**Issue by EricBatty** [brianfrankcooper/YCSB#1339] opened 2019-08-07 02:23 UTC

**Comment by busbey** [comment] 2019-09-08 05:43
duplicate of #1338 I think?

you'd need to ask the developers of the mongodb-async driver: http://www.allanbank.com/mongodb-async-driver/

**Closed by busbey** 2019-09-08 05:43 UTC
