### ISSUE TITLE
[UPDATE-FAILED], When using YCSB for MongoDB Benachmarking

### ISSUE THREAD

**Issue by tanveermadan** [brianfrankcooper/YCSB#746] opened 2016-05-10 00:11 UTC
Hi All,

I am getting [UPDATE-FAILED], when trying to do updates on MongoDB using YCSB tool

I am running below command
./bin/ycsb run mongodb-async -s -P workloads/workloada -p mongodb.url=mongodb://poc03:27091,opoc04:27091,poc05:27091/ycsb2?w=0\&readConcernLevel=local\&readPreference=primary

The results are as below
[OVERALL], RunTime(ms), 6780041.0
[OVERALL], Throughput(ops/sec), 147.49173345706907
[CLEANUP], Operations, 1.0
[CLEANUP], AverageLatency(us), 1305.0
[CLEANUP], MinLatency(us), 1305.0
[CLEANUP], MaxLatency(us), 1305.0
[CLEANUP], 95thPercentileLatency(us), 1305.0
[CLEANUP], 99thPercentileLatency(us), 1305.0
[UPDATE-FAILED], Operations, 499272.0
[UPDATE-FAILED], AverageLatency(us), 36.04590283452707
[UPDATE-FAILED], MinLatency(us), 4.0
[UPDATE-FAILED], MaxLatency(us), 9783.0
[UPDATE-FAILED], 95thPercentileLatency(us), 77.0
[UPDATE-FAILED], 99thPercentileLatency(us), 150.0
[READ], Operations, 500728.0
[READ], AverageLatency(us), 13490.998673930757
[READ], MinLatency(us), 237.0
[READ], MaxLatency(us), 1.3918207E7
[READ], 95thPercentileLatency(us), 44575.0
[READ], 99thPercentileLatency(us), 76735.0
[READ], Return=OK, 500728
[UPDATE], Operations, 0.0
[UPDATE], AverageLatency(us), NaN
[UPDATE], MinLatency(us), 9.223372036854776E18
[UPDATE], MaxLatency(us), 0.0
[UPDATE], 95thPercentileLatency(us), 0.0
[UPDATE], 99thPercentileLatency(us), 0.0
[UPDATE], Return=NOT_FOUND, 499272

I have checked the mongodb log file and find entries for the update but dont see an issue

Mon May  9 09:55:55.758 I COMMAND  [conn4306] update ycsb2.usertable query: { _id: "user6661942876597440786" } update: { $set: { field5: BinData(0, 3B5E7B2F467727457D37376E3C42273141373A3A6E3A4335333B30313B2E2E3C76225F2B2E553B382E743B4271374A75214C6F3A2A2A212838342D643C39743B32342948693E...) } } keysExamined:1 docsExamined:1 nMatched:1 nModified:1 keyUpdates:0 writeConflicts:0 numYields:1 locks:{ Global: { acquireCount: { r: 3, w: 3 } }, Database: { acquireCount: { w: 3 } }, Collection: { acquireCount: { w: 2 } }, Metadata: { acquireCount: { w: 1 } }, oplog: { acquireCount: { w: 1 } } } 23ms

I am also using the below workload config file

recordcount=12000000
operationcount=1000000
workload=com.yahoo.ycsb.workloads.CoreWorkload
readallfields=true
readproportion=0.5
updateproportion=0.5
scanproportion=0
insertproportion=0
requestdistribution=zipfian

Appreciate your help on this

Thanks,
Tanveer

**Comment by kruthar** [comment] 2016-06-03 01:36
@tanveermadan - interesting issue! I was able to easily reproduce it with a very similar command to the one you were running. The issue comes down to the fact that you are using `w=0` in your connection string. w=0 means you are making unacknowledged writes or "fire and forget" writes.

When you do this the result that comes back from making the update is -1 as per the mongodb driver javadocs:

> @return The number of documents updated. If the durability of the operation is NONE then this will be -1.

You are using unacknowledged writes which are considered having a durability of NONE. YCSB will only report a Success with a return value of 1 (1 document updated), anything else will return `NOT_FOUND`.

The workaround is to use any other value then `w=0`.

This should most likely be fixed in the driver, if the user is using `w=0` then all return values should return an `OK` status, there is simply no way to tell if the operation was successful when you fire and forget.

**Comment by tanveermadan** [comment] 2016-06-07 03:11
@kruthar Thanks of your valuable feedback !!!

**Comment by jayantgupta** [comment] 2016-06-08 18:09
@kruthar Many thanks!!, that was helpful.

**Closed** 2016-06-10 01:24 UTC

**Comment by chinglinwen** [comment] 2016-08-29 08:35
Not sure if this post it related

I do encounter the same issue, while doing jdbc kind of database testing, I found this issue is because I missed the recordscount parameter, provide recordscount  and operationcount for run command solve the problem

```
bin/ycsb run jdbc -s -P workloads/workloada -P conf/cockroachDB.properties -p operationcount=100

[READ], Return=OK, 2
[READ], Return=NOT_FOUND, 47

[READ-FAILED], Operations, 47.0
[READ-FAILED], AverageLatency(us), 1985.4255319148936
[READ-FAILED], MinLatency(us), 506.0
[READ-FAILED], MaxLatency(us), 26223.0
[READ-FAILED], 95thPercentileLatency(us), 7931.0
[READ-FAILED], 99thPercentileLatency(us), 26223.0

[UPDATE-FAILED], Operations, 49.0
[UPDATE-FAILED], AverageLatency(us), 1194.204081632653
[UPDATE-FAILED], MinLatency(us), 720.0
[UPDATE-FAILED], MaxLatency(us), 5087.0
[UPDATE-FAILED], 95thPercentileLatency(us), 4323.0
[UPDATE-FAILED], 99thPercentileLatency(us), 5087.0

[UPDATE], Return=OK, 2
[UPDATE], Return=UNEXPECTED_STATE, 49
```

The official documents didn't explain it clearly that recordcount and operationcount should provide together for run workload

**Comment by morcelicaio** [comment] 2022-03-29 14:33
Hi All. 

I'm having the same problem.

I'm trying to run the benchmark through netbeans, but I'm getting the same error of [READ-FAILED] and [UPDATE-FAILED].

I did several tests and I can't find the solution to do a clean run. Could anyone help?
I'm using a 3.6.3 version of maven and Java 8.

To try to execute it by calling the AsyncMongoDbClient class I imported the MongoDB dependencies (allanbank) and copied the classes (AsyncMongoDbClient.java, MongoDbClient.java and OptionsSupport.java) from the MongoDB Binding project into the YCSB Core project.


This is the output log

cd C:\YCSB-master\core; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_221" cmd /c "\"\"C:\\Program Files (x86)\\NetBeans\\netbeans\\java\\maven\\bin\\mvn.cmd\" -Dexec.args=\"-classpath %classpath site.ycsb.Client -db site.ycsb.AsyncMongoDbClient -s -p mongodb.url=mongodb://127.0.0.1:27017/ycsb?w=1y&journal=true -P C:\\YCSB-master\\core\\src\\main\\java\\site\\ycsb\\workloads\\workloada.properties\" -Dexec.executable=\"C:\\Program Files\\Java\\jdk1.8.0_221\\bin\\java.exe\" -Dmaven.ext.class.path=\"C:\\Program Files (x86)\\NetBeans\\netbeans\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 org.codehaus.mojo:exec-maven-plugin:1.5.0:exec\""
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building Core YCSB 0.18.0-SNAPSHOT
------------------------------------------------------------------------

--- exec-maven-plugin:1.5.0:exec (default-cli) @ core ---
Command line: -db site.ycsb.AsyncMongoDbClient -s -p mongodb.url=mongodb://127.0.0.1:27017/ycsb?w=1y&journal=true -P C:\YCSB-master\core\src\main\java\site\ycsb\workloads\workloada.properties
YCSB Client 0.18.0-SNAPSHOT

Loading workload...
Starting test.
2022-03-29 11:26:27:050 0 sec: 0 operations; est completion in 0 second 
mongo connection created with mongodb://127.0.0.1:27017/ycsb?w=1y&journal=true
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
2022-03-29 11:26:28:199 1 sec: 1000 operations; 853,24 current ops/sec; [UPDATE-FAILED: Count=516, Max=858623, Min=195, Avg=1946,45, 90=348, 99=750, 99.9=2179, 99.99=858623] [READ: Count=0, Max=0, Min=9223372036854775807, Avg=?, 90=0, 99=0, 99.9=0, 99.99=0] [CLEANUP: Count=1, Max=1575, Min=1575, Avg=1575, 90=1575, 99=1575, 99.9=1575, 99.99=1575] [UPDATE: Count=0, Max=0, Min=9223372036854775807, Avg=?, 90=0, 99=0, 99.9=0, 99.99=0] [READ-FAILED: Count=484, Max=6587, Min=95, Avg=155,82, 90=170, 99=372, 99.9=6587, 99.99=6587] 
-
-
-
-
-
[OVERALL], RunTime(ms), 1172
[OVERALL], Throughput(ops/sec), 853.2423208191126
[TOTAL_GCS_PS_Scavenge], Count, 0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.0
[TOTAL_GCS_PS_MarkSweep], Count, 0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 0
[TOTAL_GC_TIME], Time(ms), 0
[TOTAL_GC_TIME_%], Time(%), 0.0
[UPDATE-FAILED], Operations, 516
[UPDATE-FAILED], AverageLatency(us), 1946.4457364341085
[UPDATE-FAILED], MinLatency(us), 195
[UPDATE-FAILED], MaxLatency(us), 858623
[UPDATE-FAILED], 95thPercentileLatency(us), 428
[UPDATE-FAILED], 99thPercentileLatency(us), 750
[READ], Operations, 0
[READ], AverageLatency(us), NaN
[READ], MinLatency(us), 9223372036854775807
[READ], MaxLatency(us), 0
[READ], 95thPercentileLatency(us), 0
[READ], 99thPercentileLatency(us), 0
[READ], Return=NOT_FOUND, 484
[CLEANUP], Operations, 1
[CLEANUP], AverageLatency(us), 1575.0
[CLEANUP], MinLatency(us), 1575
[CLEANUP], MaxLatency(us), 1575
[CLEANUP], 95thPercentileLatency(us), 1575
[CLEANUP], 99thPercentileLatency(us), 1575
[UPDATE], Operations, 0
[UPDATE], AverageLatency(us), NaN
[UPDATE], MinLatency(us), 9223372036854775807
[UPDATE], MaxLatency(us), 0
[UPDATE], 95thPercentileLatency(us), 0
[UPDATE], 99thPercentileLatency(us), 0
[UPDATE], Return=NOT_FOUND, 516
[READ-FAILED], Operations, 484
[READ-FAILED], AverageLatency(us), 155.81611570247935
[READ-FAILED], MinLatency(us), 95
[READ-FAILED], MaxLatency(us), 6587
[READ-FAILED], 95thPercentileLatency(us), 205
[READ-FAILED], 99thPercentileLatency(us), 372
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time: 2.375 s
Finished at: 2022-03-29T11:26:28-03:00
Final Memory: 9M/245M
------------------------------------------------------------------------
