### ISSUE TITLE
YCSB hangs forever ?

### ISSUE THREAD

**Issue by schausson** [brianfrankcooper/YCSB#875] opened 2016-11-25 13:02 UTC
Hi,
I'm trying to run YCSB against my HBase cluster but cannot make it work properly...
HBase version is 1.1.2 and YCSB version is 0.11.0

Basically, I tried following commands :

`./bin/ycsb shell hbase10 -p columnfamily=cf -p table=usertable`

I get following exception :
```
...
YCSB Command Line client
Type "help" for command line help
Start with "-help" for usage info
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.lib.MutableMetricsFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.NullPointerException
        at org.apache.hadoop.hbase.TableName.valueOf(TableName.java:423)
        at com.yahoo.ycsb.db.HBaseClient10.init(HBaseClient10.java:178)
        at com.yahoo.ycsb.CommandLine.main(CommandLine.java:211)                       
```

`./bin/ycsb load hbase10 -P workloads/workloada -p columnfamily=cf -s`
I get following :
```
...
YCSB Client 0.11.0
Command line: -db com.yahoo.ycsb.db.HBaseClient10 -P workloads/workloada -p columnfamily=cf -s -load
Loading workload...
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting test.
2016-11-25 11:34:45:342 0 sec: 0 operations; est completion in 0 seconds
2016-11-25 11:34:55:318 10 sec: 0 operations; est completion in 106751991167300 days 15 hours
2016-11-25 11:35:05:318 20 sec: 0 operations; est completion in 106751991167300 days 15 hours
2016-11-25 11:35:15:318 30 sec: 0 operations; est completion in 106751991167300 days 15 hours
2016-11-25 11:35:25:318 40 sec: 0 operations; est completion in 106751991167300 days 15 hours
```
And it continues like this forever, till I interrupt the command...

It's worth saying I am able to connect to hbase using "hbase shell" command and to successfully execute commands in this shell.

So my questions are  :
Why `ycsb shell` does not work ? Did I miss some mandatory parameter ?
Is there a way to "debug" or figure out what's going on with `ycsb load` command ?

Thanks for your help,
Regards
Sebastien

**Comment by JAlejandro** [comment] 2016-11-28 16:19
Hi Sebastien

Is the table created in hbase before de ycsb execution with the same family name and table name? 

Regards, 
Alex.

**Comment by schausson** [comment] 2016-11-28 17:50
Yes, I created them before running ycsb...

**Comment by ishtartec** [comment] 2017-02-28 23:36
I had the same issue until I copied hbase-site.xml to hbase10-binding/conf/
The same issue applies to 0.12.0:

```
mkdir -p hbase10-binding/conf
cp /etc/hbase/conf.cloudera.hbase/hbase-site.xml hbase10-binding/conf
./bin/ycsb load hbase10 -P workloads/workloada -p columnfamily=family -s
```

**Comment by busbey** [comment] 2017-09-07 13:22
I think the shell not working is a duplicate of #866. the shell doesn't work with the hbase binding. You should run the load/run commands.

To get more details on what's going on with HBase connectivity, you should define a log4j.properties file and point the logging system at it.

Here's an example:

https://github.com/brianfrankcooper/YCSB/issues/860#issuecomment-252263177

**Comment by busbey** [comment] 2018-05-19 07:59
closing as stale. if this isn't a duplicate of #866 please reopen.

**Closed by busbey** 2018-05-19 07:59 UTC
Labels: question
