### ISSUE TITLE
Running YCSB from source checkout fails against 'basic' datastore binding.

### ISSUE THREAD

**Issue by IronFox** [brianfrankcooper/YCSB#336] opened 2015-07-02 13:50 UTC
Heya!
I tried this both on Windows and Linux. YCSB Compiles fine from original code, but when I try to run './bin/ycsb shell basic' the following errors will pop up in the shell:

[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:basic-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
[ERROR]  Attempting to generate a classpath from Maven failed with return code '1'. The output from Maven follows, try running 'mvn -DskipTests package dependency:build=classpath' on your own and correct errors.

mvn output:
[INFO] Scanning for projects...
[ERROR] Could not find the selected project in the reactor: com.yahoo.ycsb:basic-binding -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

The mvn output appears to be generated when executing other ycsb operations as well although I have not tried many. YCSB without any parameters executes fine. I am not overly familiar with Maven, hence I have no idea what the problem is, or how to fix it. The relative consistency between Ubuntu and Windows, and the simplicity of the executed instructions may indicate it's a problem with Maven and/or YCSB rather than what I did. Anyway, any help is appreciated. I must build the project from code since I aim to implement new features I need for a rather specific test. For now, no modifications have been implemented, however.

Cheers,
Stefan Elsen

**Comment by busbey** [comment] 2015-07-02 14:21
ah. the problem is the way we guess what to include in the classpath when running out of a source checkout. We essentially look for a module named "%datastore%-binding", but basic is included in core.

Hurm. we could either pull basic into a module that matched all the other datastore bindings or add some special casing in bin/ycsb. What do you think @cmccoy, @cmatser?

As a current work-around, you can do 'mvn package' from the top level and then make use of the distribution tgz artifact made in `distribution/target/`.

If things work for you on Windows, we'd love a short set of instructions on what you had to do. It's on my TODO list for hte current release process, but so far I haven't made any progress.

**Comment by cmatser** [comment] 2015-07-02 17:58
Well, I grew up on unix, but I develop on windows, but I deploy on unix.  What a mixed up world we live in!  :)  Even when I'm on windows, I'm running cygwin which gives me the unix tools I'm familiar with, like "vi".  Can we start a "emacs" vs "vi" debate?  Probably not the right venue.  :)

What I did when I was running YCSB on windows was I tried bin/ycsb.  When that failed, I looked at what it was trying to do.  Then I created my own windows .bat script to run the db binding I wanted to run.  It's a one-off.

What I would like to see is the ability to run from source.  I never touched the production version and wonder about its usefulness.  I disagree with the python script.  If all you're trying to accomplish is to run on windows, then I don't think you should require a windows python install.  My preference would be to see shell scripts, one for unix and one for windows, like I've seen on other cross platform projects (tomcat).  I feel this gives the best user experience.

$0.02

Chrisjan

**Comment by busbey** [comment] 2015-07-02 18:38
> What I would like to see is the ability to run from source. I never touched the production version and
> wonder about its usefulness.

Well, in general we're going to try to push folks towards the releases, because it will make it easier to ensure they're using a version we have some confidence in.

>  I disagree with the python script. If all you're trying to accomplish is to run on windows, then I don't 
> think you should require a windows python install. My preference would be to see shell scripts, one for 
> unix and one for windows, like I've seen on other cross platform projects (tomcat). I feel this gives the 
> best user experience.

We'll have to work through things, but I'm on the same side of this argument. There's actually a project I'm involved in starting up over at the Apache Software Foundation that has cross-platform shell bindings as a goal, so I'm hoping we can use that once it matures a little.

**Comment by busbey** [comment] 2015-07-02 18:40
For the problem at hand, the main issue I see with moving the basic binding into a module is that it would no longer be included in the datastore specific artifacts we're creating now. Getting it back in there could be done by futzing with the binding-parent, but that sounds like a headache for not much gain.

**Comment by IronFox** [comment] 2015-07-03 07:41
Okies, the idea with 'mvn package' and using distribution/target/ seemed to have worked both on Ubuntu and Windows without much fuzz. At least the basic shell command started without any more hickups. As for what I had to do, the whole thing was pretty much the same on Windows and Linux. I obviously had to install Python and Maven, and of course something to extract the tar/gz file, as well as link the JDK via JAVA_HOME manually. But other than that, it ran out of the box. The error message when running 'ycsb shell basic' from code on Windows looks somewhat more like what leileiway described, but when manually issuing the mvn commands, it looked again exactly as on Linux.
So yeah, that worked. Many thanks. I'll begin implementing my new functionality straight away. If that works, and proves useful, I'll submit the modifications for inclusion into the main branch as you see fit.

Cheers,
Stefan

**Comment by busbey** [comment] 2015-08-04 13:22
To close this out we need to add an exception for the 'basic' store in our classpath calculation.

**Closed** 2015-10-23 05:32 UTC
