### ISSUE TITLE
ycsb load error

### ISSUE THREAD

**Issue by amneet456** [brianfrankcooper/YCSB#227] opened 2015-04-15 12:58 UTC
I am not able to load and run my data in cassandra using ycsb while running ycsb on windows.
 I used command

python ycsb load cassandra-10 -P C:\Users\Faria\Desktop\Test\YCSB\workloads\workloada -s > load.log
after using above command load file is created in log but it is showing 
  	 
Missing property: workload java -cp C:\ycsb\cassandra-binding\lib\cassandra-binding-0.1.4.jar;C:\ycsb\core\lib\core-‌​0.1.4.jar;C:\ycsb\gemfire-binding\conf;C:\ycsb\hbase-binding\conf;C:\ycsb\infinis‌​pan-binding\conf;C:\ycsb\jdbc-binding\conf;C:\ycsb\nosqldb-binding\conf;C:\ycsb\v‌​oldemort-binding\conf com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.CassandraClient10 -P C:\ycsb\workloads\workloada -s -load –

**Comment by nielsdevos** [comment] 2015-04-15 13:19
not sure if that is the problem but for cassandra you have to make a keyspace "usertable" and column family "data" and use the command
./bin/ycsb load cassandra-10 -P workloads/workloada -p hosts=localhost -p columnfamily=data

this works for me.

**Comment by amneet456** [comment] 2015-04-15 13:21
where to use this command.. in cmd or somewhere else... i am implementing ycsb through python.

**Comment by nielsdevos** [comment] 2015-04-15 13:33
then i guess it's 
python ycsb load cassandra-10 -P workloads/workloada -p hosts=localhost -p columnfamily=data

**Comment by amneet456** [comment] 2015-04-15 14:15
it is showig me. the system cannot find the path specified. 
which hosts to use??

**Comment by amneet456** [comment] 2015-04-15 14:16
it is showig me. the system cannot find the path specified. 
which hosts to use??

**Comment by amneet456** [comment] 2015-04-15 14:18
![capture](https://cloud.githubusercontent.com/assets/11829568/7160688/49753ec2-e3a8-11e4-92b9-b3e0cb1bd111.JPG)

**Comment by nielsdevos** [comment] 2015-04-15 14:21
try this
python ycsb load cassandra-10 -P C:\Users\Faria\Desktop\Test\YCSB\workloads\workloada -p hosts=localhost -p columnfamily=data

**Comment by amneet456** [comment] 2015-04-15 14:27
![la](https://cloud.githubusercontent.com/assets/11829568/7160873/7e785090-e3a9-11e4-8d12-4b225f5ea9c3.JPG)

**Comment by nielsdevos** [comment] 2015-04-15 14:29
are you sure your workloads are on that path and not on C:\ycsb\workloads\workloada?

**Comment by amneet456** [comment] 2015-04-15 14:33
yes. our workloada file is in c:\ycsb\workloads\workloada. But it is showing missing property workload

**Comment by nielsdevos** [comment] 2015-04-15 14:36
so you've tried this already?
python ycsb load cassandra-10 -P C:\ycsb\workloads\workloada -p hosts=localhost -p columnfamily=data

**Comment by amneet456** [comment] 2015-04-15 14:38
yes . we have already tried this.

**Comment by cmatser** [comment] 2015-04-15 16:16
This line should be in your "workloada" file:

workload=com.yahoo.ycsb.workloads.CoreWorkload

If not add it.  If it is, try adding the property directly on the command line like:

python ycsb load cassandra-10 -P C:\ycsb\workloads\workloada -p workload=com.yahoo.ycsb.workloads.CoreWorkload -p hosts=localhost -p columnfamily=data

This is redundant and should not be necessary, but it may point to the real problem like, is the file readable?  I'm thinking there must be something with finding the "workloada" file.

Good luck.
Chrisjan

**Comment by amneet456** [comment] 2015-04-15 16:34
still same error. missing property:workload :(

**Comment by amneet456** [comment] 2015-04-15 17:15
![ff](https://cloud.githubusercontent.com/assets/11829568/7164813/817ca3f6-e3c0-11e4-8bc2-1fd31a9aacec.JPG)

**Comment by amneet456** [comment] 2015-04-15 17:16
now it is showing number format exception.. in the above screenshot

**Comment by nielsdevos** [comment] 2015-04-15 17:19
I think your workloads are just wrong. Take a better look at the example ones.

**Comment by amneet456** [comment] 2015-04-15 17:26
can you help us. please its urgent.

**Comment by cmatser** [comment] 2015-04-15 18:44
I think I know the cause of the problem.  I think this is a dos vs unix file format.  The reason I say this is based on your last screenshot.  It errors on the input string "0insertproportion=10hosts=127.0.0.1" .  This is obviously the wrong string and it not a string on your command line.  So, it must be in your workload file.

UNIX files end lines with just a newline.  DOS files end with a newline and carriage return.  I believe workload files you got from github are in UNIX file format and you are obviously running on Windows.  Try recreating the files with notepad or other Windows editor.

Chrisjan

**Comment by amneet456** [comment] 2015-04-18 16:27
you were a great help to us. thankyou so much. :)

**Comment by busbey** [comment] 2015-05-29 07:31
closed as solved. if you are still having problems please reopen.

**Closed by busbey** 2015-05-29 07:31 UTC

**Comment by bikashbanjara** [comment] 2015-06-18 17:33
"Try recreating the files with notepad or other Windows editor." what does it mean? plz can you tell me how it can be done?

**Comment by cmatser** [comment] 2015-06-18 21:19
Copy-n-paste into Notepad and then save.

**Comment by bikashbanjara** [comment] 2015-06-19 02:02
![document](https://cloud.githubusercontent.com/assets/7991748/8246043/6a76200a-1657-11e5-80ed-dfd1e4fa091a.jpg)

**Comment by bikashbanjara** [comment] 2015-06-19 02:04
still some error.....the system cannot find the file specified...

**Comment by busbey** [comment] 2015-06-19 02:45
@bikashbanjara please open a new issue for your problem.

**Comment by bikashbanjara** [comment] 2015-06-19 04:52
i m using windows 8.1 where the required sw i m using java 1.7.0_79, apache maven 3.3.3, python 2.7.10, git version 1.9.5.msysgit.1, apache cassandra 2.1.6 and ycsb 0.1.4

and the path of ycsb C:\YCSB\workloads\workloada

i have edited the workload file by assinging the hosts=127.0.0.1

**Comment by busbey** [comment] 2015-06-20 01:26
just a heads up, but we have a known issue currently with Cassandra 2.1 (ref #293 )

could you try to reproduce your issue with our [current release candidate for YCSB 0.2.0](https://github.com/brianfrankcooper/YCSB/releases/tag/0.2.0-RC1) ?

Also, can you give me the md5 sum of the ycsb tarball you used for 0.1.4?
