### ISSUE TITLE
ycsb error

### ISSUE THREAD

**Issue by amneet456** [brianfrankcooper/YCSB#224] opened 2015-04-07 05:52 UTC
i tried to run command 
python ycsb shell basic 
to check wether ycsb is properly configured. but it is giving me error. could not find or load main class com.yahoo.ycsb.commndLine.
can anyone tell me solution?

**Comment by busbey** [comment] 2015-05-17 08:35
duplicate of #223

**Closed by busbey** 2015-05-17 08:35 UTC

**Comment by amneet456** [comment] 2015-05-17 11:47
yup....  i have already done with this :)
