### ISSUE TITLE
Workload 'e' failure when using an operation count that causes overflow for the zipfian distribution.

### ISSUE THREAD

**Issue by allanbank** [brianfrankcooper/YCSB#431] opened 2015-10-11 01:20 UTC
Workload 'e' will stall when running a workload when the record count is close to 2^31.

Can be reproduced using a workload command similar to:
```
bin/ycsb run <binding> -P workloads/workloade" -p recordcount=0 -p operationcount=429496729
```

Current working theory is that the overflow of the value causes the zipfian distribution to enter an infinite loop. This is evidenced by all of the threads stuck with a stack trace similar to the following.

```
"Thread-21" prio=10 tid=0x00007f1cb048e800 nid=0x4370 runnable [0x00007f1c6215b000]
   java.lang.Thread.State: RUNNABLE
	at com.yahoo.ycsb.workloads.CoreWorkload.nextKeynum(CoreWorkload.java:624)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionScan(CoreWorkload.java:714)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:579)
	at com.yahoo.ycsb.ClientThread.run(Client.java:329)
```

See the discussion at the end of #427 for details.

**Comment by busbey** [comment] 2015-10-11 01:57
it'd be great if we work out what the max safe values for those currently are.

**Comment by busbey** [comment] 2015-10-11 02:42
ugh a thousand times. it looks like I figured all of this out when testing HBase back in August. Sorry everyone that I often compartmentalize while working on Accumulo vs HBase. :person_frowning: 

closing as a duplicate of #384

**Closed by busbey** 2015-10-11 02:42 UTC
