### ISSUE TITLE
elasticsearch7.x YCSB

### ISSUE THREAD

**Issue by madonhe** [brianfrankcooper/YCSB#1346] opened 2019-08-26 07:06 UTC
My elasticsearch  is 7.x
use elasticsearch5-rest mode read data "[types removal] Specifying types in search requests is deprecated."]
I know 7.x type remove,but I won't change Java code
Do you have any suggestions for me?

**Comment by busbey** [comment] 2019-09-08 05:40
duplicate of #1348

**Closed by busbey** 2019-09-08 05:40 UTC
