### ISSUE TITLE
Maven 3 

### ISSUE THREAD

**Issue by Srija2000** [brianfrankcooper/YCSB#1537] opened 2021-05-03 03:20 UTC
If I use maven3 also I am finding the same issue 
Build failure
![Screenshot (262)](https://user-images.githubusercontent.com/60351574/116838615-97a90480-abec-11eb-839c-94b81288f0de.png)

**Comment by stefanocereda** [comment] 2021-06-28 09:09
I am getting the exact same error on my pc, where I have arch with maven 3.8.1.
However, running it on ubuntu with maven 3.6.3 works perfectly.

**Comment by busbey** [comment] 2022-03-08 04:37
marking this as a duplicate of #1557 because there's a good explanation there of what's going on.

**Closed by busbey** 2022-03-08 04:37 UTC
