### ISSUE TITLE
Cassandra - error on create keyspace

### ISSUE THREAD

**Issue by Hadi14** [brianfrankcooper/YCSB#531] opened 2015-12-12 17:50 UTC
Hi
when i create keyspace got this error , how can fix it?
 create keyspace usertable with placement_strategy = 'org.apache.cassandra.locator.SimpleStrategy' and strategy_options = {replication_factor:1}; 

<code>SyntaxException: ErrorMessage code=2000 [Syntax error in CQL query] message="line 1:140 no viable alternative at input ':' (... 'org.apache.cassandra.locator.SimpleStrategy' and  strategy_options = {[replication_factor]:...)">  </code>

**Comment by busbey** [comment] 2015-12-12 19:28
Hi @Hadi14, is this error happening when you attempt to use cqlsh?

**Comment by kruthar** [comment] 2015-12-13 03:22
@Hadi14 - as per the other thread you are using Cassandra 2.2. The create keyspace line you posted is from the cassandra-binding which is meant for Cassandra 1. You should be using the cassandra2-binding the syntax there has changed. You can see the new setup script for Cassandra 2 here: https://github.com/brianfrankcooper/YCSB/tree/master/cassandra2. Go ahead and try that.

**Comment by Hadi14** [comment] 2015-12-13 15:15
Hi @busbey 
yes this error happening when i create keyspace  on cqlsh.

**Comment by busbey** [comment] 2015-12-14 03:43
closing this as a duplicate of #530, since it seems to be an extension of the issues you encountered on that issue. Please reopen if I've misinterpreted things.

**Closed by busbey** 2015-12-14 03:43 UTC
